name: Master to Leader check
on: pull_request
jobs:
  master-leader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Words Really Matter
        uses: jjasghar/actions-words-really-matter@v1.0.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
